// Dictionnaire FR -> EN des noms de Pokemon, pour traduire un nom devine
// depuis un titre Vinted (souvent en francais) avant d'interroger l'API
// pokemontcg.io (base en anglais/japonais).
// Couverture: principalement generation 1 (les plus recherchees en vintage),
// a completer au fil du temps pour les generations suivantes.
export const FR_TO_EN = {
  "bulbizarre": "Bulbasaur",
  "herbizarre": "Ivysaur",
  "florizarre": "Venusaur",
  "salameche": "Charmander",
  "reptincel": "Charmeleon",
  "dracaufeu": "Charizard",
  "carapuce": "Squirtle",
  "carabaffe": "Wartortle",
  "tortank": "Blastoise",
  "chenipan": "Caterpie",
  "chrysacier": "Metapod",
  "papilusion": "Butterfree",
  "aspicot": "Weedle",
  "coconfort": "Kakuna",
  "dardargnan": "Beedrill",
  "roucool": "Pidgey",
  "roucoups": "Pidgeotto",
  "roucarnage": "Pidgeot",
  "rattata": "Rattata",
  "rattatac": "Raticate",
  "piafabec": "Spearow",
  "rapasdepic": "Fearow",
  "abo": "Ekans",
  "arbok": "Arbok",
  "pikachu": "Pikachu",
  "raichu": "Raichu",
  "sabelette": "Sandshrew",
  "sablaireau": "Sandslash",
  "melofee": "Clefairy",
  "melodelfe": "Clefable",
  "goupix": "Vulpix",
  "feunard": "Ninetales",
  "rondoudou": "Jigglypuff",
  "grodoudou": "Wigglytuff",
  "nosferapti": "Zubat",
  "nosferalto": "Golbat",
  "mystherbe": "Oddish",
  "ortide": "Gloom",
  "rafflesia": "Vileplume",
  "paras": "Paras",
  "parasect": "Parasect",
  "mimitoss": "Venonat",
  "aeromite": "Venomoth",
  "taupiqueur": "Diglett",
  "triopikeur": "Dugtrio",
  "miaouss": "Meowth",
  "persian": "Persian",
  "psykokwak": "Psyduck",
  "akwakwak": "Golduck",
  "ferosinge": "Mankey",
  "colossinge": "Primeape",
  "caninos": "Growlithe",
  "arcanin": "Arcanine",
  "ptitard": "Poliwag",
  "tetarte": "Poliwhirl",
  "tortipouss": "Poliwrath",
  "abra": "Abra",
  "kadabra": "Kadabra",
  "alakazam": "Alakazam",
  "machoc": "Machop",
  "machopeur": "Machoke",
  "mackogneur": "Machamp",
  "chetiflor": "Bellsprout",
  "boustiflor": "Weepinbell",
  "empiflor": "Victreebel",
  "tentacool": "Tentacool",
  "tentacruel": "Tentacruel",
  "racaillou": "Geodude",
  "gravalanch": "Graveler",
  "grolem": "Golem",
  "ponyta": "Ponyta",
  "galopa": "Rapidash",
  "ramoloss": "Slowpoke",
  "flagadoss": "Slowbro",
  "magneti": "Magnemite",
  "magneton": "Magneton",
  "canarticho": "Farfetch'd",
  "doduo": "Doduo",
  "dodrio": "Dodrio",
  "otaria": "Seel",
  "lamantine": "Dewgong",
  "tadmorv": "Grimer",
  "grotadmorv": "Muk",
  "kokiyas": "Shellder",
  "crustabri": "Cloyster",
  "fantominus": "Gastly",
  "spectrum": "Haunter",
  "ectoplasma": "Gengar",
  "onix": "Onix",
  "soporifik": "Drowzee",
  "hypnomade": "Hypno",
  "kraby": "Krabby",
  "krabboss": "Kingler",
  "voltorbe": "Voltorb",
  "electrode": "Electrode",
  "nonoclus": "Exeggcute",
  "noadkoko": "Exeggutor",
  "osselait": "Cubone",
  "ossatueur": "Marowak",
  "kicklee": "Hitmonlee",
  "tygnon": "Hitmonchan",
  "excelangue": "Lickitung",
  "smogo": "Koffing",
  "smogogo": "Weezing",
  "rhinocorne": "Rhyhorn",
  "rhinoferos": "Rhydon",
  "leveinard": "Chansey",
  "saquedeneu": "Tangela",
  "kangourex": "Kangaskhan",
  "hypotrempe": "Horsea",
  "hypocean": "Seadra",
  "poissirene": "Goldeen",
  "poissoroy": "Seaking",
  "stari": "Staryu",
  "staross": "Starmie",
  "insecateur": "Scyther",
  "tauros": "Tauros",
  "magicarpe": "Magikarp",
  "leviator": "Gyarados",
  "lokhlass": "Lapras",
  "metamorph": "Ditto",
  "evoli": "Eevee",
  "aquali": "Vaporeon",
  "voltali": "Jolteon",
  "pyroli": "Flareon",
  "porygon": "Porygon",
  "amonita": "Omanyte",
  "amonistar": "Omastar",
  "kabuto": "Kabuto",
  "kabutops": "Kabutops",
  "ptera": "Aerodactyl",
  "ronflex": "Snorlax",
  "artikodin": "Articuno",
  "electhor": "Zapdos",
  "sulfura": "Moltres",
  "minidraco": "Dratini",
  "draco": "Dragonair",
  "dracolosse": "Dragonite",
  "mewtwo": "Mewtwo",
  "mew": "Mew",
};

/**
 * Traduit un nom devine (potentiellement en francais) vers l'anglais si on a
 * une correspondance connue. Sinon retourne le nom original tel quel (il
 * pourrait deja etre en anglais, ou correspondre a une generation non couverte).
 */
export function translateToEnglish(guessedName) {
  if (!guessedName) return guessedName;
  const lower = guessedName.toLowerCase().trim();
  return FR_TO_EN[lower] || guessedName;
}
